#22 triton-docker does not handle container args containing spaces #17 triton-compose should support newer docker-compose (#23)
Reviewed by: Dan McDonald <danmcd@mnx.io>

diff --git a/triton-docker b/triton-docker
--- a/triton-docker
+++ b/triton-docker
@@ -1,4 +1,12 @@
 #!/bin/bash
+
+# This Source Code Form is subject to the terms of the Mozilla Public
+# License, v. 2.0. If a copy of the MPL was not distributed with this
+# file, You can obtain one at https://mozilla.org/MPL/2.0/.
+
+# Copyright 2017 Joyent, Inc.
+# Copyright 2023 MNX Cloud, Inc.
+
 set -e -o pipefail
 
 triton_docker_version=1.12.6
@@ -17,8 +25,8 @@ function checkCurlInstalled () {
 # Check if the Docker binary (named triton-docker-helper)
 # and Docker Compose (named triton-compose-helper) are installed and executable
 function checkDockerInstalled () {
-    if 
-        [ ! -f /usr/local/bin/triton-docker-helper ] || 
+    if
+        [ ! -f /usr/local/bin/triton-docker-helper ] ||
         [ ! -x /usr/local/bin/triton-docker-helper ] ||
         [ "${triton_docker_version}," != "$(/usr/local/bin/triton-docker-helper -v | awk '{print $3}')" ] ||
         [ ! -f /usr/local/bin/triton-compose-helper ] ||
@@ -26,6 +34,7 @@ function checkDockerInstalled () {
         [ "${triton_compose_version}," != "$(/usr/local/bin/triton-compose-helper -v | awk '{print $3}')" ]
     then
         echo 'Additional or updated components are required.'
+        # shellcheck disable=SC2016
         echo 'Please run `sudo triton-docker-install` to continue.'
         echo
         exit 1
@@ -48,6 +57,18 @@ function install () {
     rm -Rf /tmp/triton-docker
     chmod +x /usr/local/bin/triton-docker-helper
 
+    # Install a good root CA store for docker-compose
+    # We'll use the directory where triton profile outputs docker certs.
+    if ! [[ -d ~/.triton/docker ]]; then
+        mkdir -p ~/.triton/docker
+    fi
+    curl -sf -o ~/.triton/docker/cacert.pem https://curl.haxx.se/ca/cacert.pem
+    cert_ret=$?
+    if (( cert_ret != 0 )); then
+        echo 'Failed to install CA certs for docker-compose. This is a curl error.' >&2
+        echo "See the curl man page for error $cert_ret for help diagnosing this error." >&2
+    fi
+
     echo "The triton-docker-helper is now installed."
     echo
 
@@ -63,13 +84,16 @@ function install () {
 function currentProfile () {
     if [ -n "$TRITON_PROFILE" ]
     then
+        # shellcheck disable=SC2016
         local profile_source='via env var; use `eval "$(triton env <profile name>)"` to change'
     else
+        # shellcheck disable=SC2016
         local profile_source='default; use `triton profile set <profile name>` to change'
     fi
 
     # Get and the user's account information and CloudAPI URL for parsing later
-    local triton_account="$(triton account get)"
+    local triton_account
+    triton_account="$(triton account get)"
 
     echo "Executing in '$(triton profile get | awk 'NR == 1 {print $2}')' (${profile_source})"
 
@@ -90,6 +114,10 @@ function currentProfile () {
 
 # Set env vars to make using CNS easier
 function cnsEnvVars () {
+    local triton_account
+    local triton_url
+    local triton_account_uuid
+    local triton_dc
 
     # If the CNS env vars are already set, don't bother continuing
     if [ -n "$TRITON_CNS_SEARCH_DOMAIN_PUBLIC" ] && [ -n "$TRITON_CNS_SEARCH_DOMAIN_PRIVATE" ]
@@ -98,8 +126,8 @@ function cnsEnvVars () {
     fi
 
     # Get and the user's account information and CloudAPI URL for parsing later
-    local triton_account="$(triton account get)"
-    local triton_url="$(triton profile get | awk -F"/" '/url:/{print $3}')"
+    triton_account="$(triton account get)"
+    triton_url="$(triton profile get | awk -F"/" '/url:/{print $3}')"
 
     # Do not continue if the target is not a Triton Public Cloud data center
     if [ ! ".api.joyent.com" == "${triton_url: -15}" ]
@@ -108,12 +136,12 @@ function cnsEnvVars () {
     fi
 
     # Get the user's UUID
-    local triton_account_uuid="$(echo "${triton_account}" | awk -F": " '/^id:/{print $2}')"
+    triton_account_uuid="$(echo "${triton_account}" | awk -F": " '/^id:/{print $2}')"
 
     # Get current data center name
     # Note: this makes assumptions that work in our public cloud, but might not work elsewhere
     # Further note: set TRITON_CNS_SUFFIX_PUBLIC and TRITON_CNS_SUFFIX_PRIVATE to work around this
-    local triton_dc="$(echo "${triton_url}" | awk -F'.' '{print $1}')"
+    triton_dc="$(echo "${triton_url}" | awk -F'.' '{print $1}')"
 
     # Set the CNS base for public and private names
     # Note, this also makes assumptions that only work in our public cloud
@@ -135,21 +163,24 @@ then
 fi
 
 # Change behavior based on the calling name of this executable
-case "$(basename $0)" in
+case "$(basename "$0")" in
     triton-docker)
         checkAll &&
         eval "$(triton env)" &&
         cnsEnvVars &&
-        exec /usr/local/bin/triton-docker-helper $@
+        exec /usr/local/bin/triton-docker-helper "$@"
         ;;
     triton-compose)
         checkAll &&
         eval "$(triton env)" &&
         export COMPOSE_HTTP_TIMEOUT=750 &&
+        export CURL_CA_BUNDLE=~/.triton/docker/cacert.pem
         cnsEnvVars &&
-        exec /usr/local/bin/triton-compose-helper $@
+        exec /usr/local/bin/triton-compose-helper "$@"
         ;;
     triton-docker-install)
         install
         ;;
+    *)
+        echo "Unsupported: $(basename "$0")"
 esac
